import { API_ENDPOINTS } from '../config/env';

export const endpoints = {
  ...API_ENDPOINTS,
  USERS: API_ENDPOINTS.USERS,
  MESOCYCLES: API_ENDPOINTS.MESOCYCLES,
  PLAN_INSTANCES: API_ENDPOINTS.PLAN_INSTANCES,
  WORKOUT_INSTANCES: API_ENDPOINTS.WORKOUT_INSTANCES,
  EXERCISES: API_ENDPOINTS.EXERCISES,
  DASHBOARD: API_ENDPOINTS.DASHBOARD,
};


